# Generated by Django 4.2.17 on 2024-12-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_triggers', models.TextField(blank=True, help_text='Include a comma separated list of new Triggers to create them, e.g. "apple, banana, pear"', null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='NotRelevantReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_search_query', models.TextField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notrelevantreports', to='researchdata.prompt')),
            ],
            options={
                'ordering': ['-meta_created_datetime'],
            },
        ),
    ]
