# Generated by Django 4.2.17 on 2025-04-07 07:35

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_datainsert_notrelevantreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'ordering': ('-meta_lastupdated_datetime', django.db.models.functions.text.Upper('trigger_text'), 'id')},
        ),
    ]
